[DEFAULT]
#options for the UI, such as the title of the page, the options for the LLM, use case, and GROQ model.
PAGE_TITLE = LangGraph: Build Stateful Agentic AI graph
LLM_OPTIONS = Groq
USECASE_OPTIONS = Basic Chatbot
GROQ_MODEL_OPTIONS = openai/gpt-oss-120b, groq/compound-mini